config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  resources :users, only: [:new, :create, :show]

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google_auth' 
  get '/characters/main_characters' => 'characters#main_characters'

  resources :worlds
  resources :stories
  resources :stories, only: [:show] do
    resources :characters, only: [:new, :index, :show, :edit, :destroy]
  end
  resources :characters
end

app/models/world.rb
class World < ApplicationRecord
    validates :name, presence: true, uniqueness: {scope: :user}
    
    belongs_to :user
    has_many :characters
    has_many :stories, through: :characters

    scope :most_recent, -> {order('created_at DESC')}
    scope :search, -> (search){where('name LIKE?', "%#{search}%")}
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
    before_action :require_login
    before_action only: [:edit, :update] do
        authorize_to_edit(World)
    end

    def index
        if params[:search]
            @worlds = World.search(params[:search]).most_recent
        else    
            @worlds = World.most_recent
        end

    end

    def new
        @world = World.new
    end

    def create
        @world = current_user.worlds.build(world_params)
        if @world.save
            redirect_to world_path(@world)
        else
            render 'new'
        end
    end

    def show
        @world = World.find_by(id: params[:id]) 
    end


    def edit
        @world = World.find_by(id: params[:id])
    end

    def update
        @world = World.find_by(id: params[:id])
        @world.update(world_params)
        redirect_to world_path(@world)
    end

    def destroy
        @world = World.find_by_id(params[:id])
        @world.destroy
        redirect_to user_path(current_user)
    end

    private

    def world_params
        params.require(:world).permit(:name, :scale, :description, :user_id)
    end

end

app/views/worlds/_form.html.erb
<%= form_for @world do |f| %>
    <div class="form-group">
        <%= f.label :name, "Setting Name: " %><br>
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :scale, "Scale: " %>
        <%= f.select :scale, options_for_select([["Multiverse"], ["Universe"], ["Galaxy"], ["Planet"], ["Continent"], ["Nation"], ["Region"], ["City"], ["Town"], ["Building"], ["Vehicle"], ["Other"]], :selected=>@world.scale), class: "form-control" %><br>
    </div>

    <div class="form-group">
        <%= f.label :description, "Description:" %><br>
        <%= f.text_area :description, class: "form-control" %><br>
    </div>

    <%= submit_tag "Forge Your World", class: "btn btn-primary" %>
<% end %>

app/views/worlds/edit.html.erb
<div class="title-container">
    <h1>Edit <%= @world.name %></h1>
</div>
<%= render 'form' %>
<br>
<%= link_to "Back To World", world_path(@world) %>

app/views/worlds/index.html.erb
<div class="title-container">
    <h1>Explore the Multiverse</h1>
</div>

<% flash.each do |type, msg| %>
    <div>
        <b><%= msg %></b>
        <br><br>
    </div>
<% end %>

<%= form_tag '/worlds', method: :get do %>
    <label>Search: </label>
    <input type="text" id="search" name="search">
    <input type="submit" value="Submit">
<% end %>
<br>
<% @worlds.each do |w| %>
    <p><%= link_to w.name, world_path(w) %><br>
    Drafted by <%= w.user.author_name %> on <%= w.created_at.strftime("%B %e, 20%y") %>
    </p>
<% end %>

app/views/worlds/new.html.erb
<div class="title-container">
    <h1>Build A World</h1>
</div>

<p>Your World is the over-arching setting of your story - and can be as large as an epic multiverse, or as small as a single building. Tell stories at every scale!</p>
<p>You can create multiple worlds if your story spans across many settings, but to start, we suggest going as big as possible, then adding locations within that larger setting later.</p>
<br>
<%= render partial: 'shared/errors', locals: {object: @world} %>
<%= render 'form' %>

app/views/worlds/show.html.erb
<div class="title-container">
    <h1><%= @world.name %></h1>
    <% if current_user.id == @world.user_id.to_i %>
        <p><%= link_to "Edit World", edit_world_path(@world), class: "btn btn-default" %>
        <%= link_to "Delete World", world_path(@world), method: :delete, class: "btn btn-default" %></p>
    <% end %>
</div>    
<p><b>Scale:</b> <%= @world.scale %></p>
<p><b>Characters of <%= @world.name %>: </b></p>
<% if @world.characters.empty? %>
    <p><i>No Characters Added to Associated Stories</i></p>
<% else %>
    <% @world.characters.order_by_name.each do |c| %>
        <ul>
            <li><%= link_to c.name, story_character_path(c.story, c) %></li>
        </ul>
    <% end %>
<% end %>
<p><b>Description:</b></p> 
<%= field_completed?(@world, :description, :empty?) %>