config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  resources :users, only: [:new, :create, :show]

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google_auth' 
  get '/characters/main_characters' => 'characters#main_characters'

  resources :worlds
  resources :stories
  resources :stories, only: [:show] do
    resources :characters, only: [:new, :index, :show, :edit, :destroy]
  end
  resources :characters
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    validates :author_name, presence: true
    validates :email, presence: true, uniqueness: true

    has_secure_password

    has_many :stories
    has_many :worlds

    def self.google_create(auth)
        self.find_or_create_by(username: auth[:info][:email]) do |u|
            u.password = SecureRandom.hex
            u.email = auth[:info][:email]
            u.author_name = auth[:info][:name]   
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def show
        if !logged_in?
            redirect_to root_path
        else
            @user = User.find_by(id: params[:id])
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :author_name, :email, :password, :password_confirmation)
    end
end

app/views/users/new.html.erb
<div class="title-container">
    <h1>Become An Author</h1>
</div>

<%= render partial: 'shared/errors', locals: {object: @user} %>

<%= form_for @user do |f| %>
    <%= f.label :username, "Username: " %>
    <%= f.text_field :username %><br><br>
    <%= f.label :author_name, "Pseudonym/Author Name: " %>
    <%= f.text_field :author_name %><br><br>
    <%= f.label :email, "Contact E-mail: " %>
    <%= f.text_field :email %><br><br>
    <%= f.label :password, "Password: " %>
    <%= f.password_field :password %><br><br>
    <%= f.label :password_confirmation, "Password Confirmation: " %>
    <%= f.password_field :password_confirmation %><br><br>
    <%= submit_tag "Create Author" %>
<% end %>

app/views/users/show.html.erb
<div class="title-container">
    <h2>Welcome aboard, <%= @user.username %>!</h2>
</div>

<p>This is your Story Quill, where you can create new characters, stories and even worlds!</p>

<% if current_user.worlds.empty? || current_user.stories.empty? %>
    <p>New to LoreScroll? Let's get started.</p>
    <ol>
        <li><%= link_to "Create your world", new_world_path %>, a setting for your story to flourish in.</li> 
        <li><%= link_to "Tell your story", new_story_path %> and leave your audience enraptured.</li>
        <li>Fill that story with characters and link them to your worlds.</li>  
    </ol>
<% else %>
    <br>
<% end %>
<br>
<div class="content-box">
    <div class="content">
        <h3>Your Worlds</h3>
        <% if @user.worlds.exists? %>
            <% @user.worlds.each do |w| %>
                <li><%= link_to w.name, world_path(w) %></li><br>
            <% end %>
        <% else %>
            <p>No Worlds Added</p>
        <% end %>
    </div>
</div>
<br>
<div class="content-box">
    <div class="content">
        <h3>Your Stories</h3>
            <% if @user.stories.exists? %>
                <% @user.stories.each do |s| %>
                    <li><%= link_to s.title, story_path(s) %></li><br>
                <% end %>
            <% else %>
                <p>No Stories Added</p>
            <% end %>
    </div>
</div>