config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  resources :users, only: [:new, :create, :show]

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google_auth' 
  get '/characters/main_characters' => 'characters#main_characters'

  resources :worlds
  resources :stories
  resources :stories, only: [:show] do
    resources :characters, only: [:new, :index, :show, :edit, :destroy]
  end
  resources :characters
end

app/models/story.rb
class Story < ApplicationRecord
    validates :title, presence: true, uniqueness: {scope: :user}
    
    belongs_to :user 
    has_many :characters, dependent: :destroy 
    has_many :worlds, -> {distinct}, through: :characters
    has_many :story_genres
    has_many :genres, through: :story_genres
    accepts_nested_attributes_for :genres

    scope :most_recent, -> {order('created_at DESC')}

    def genres_attributes=(genre_attributes)
        genre_name = genre_attributes["0"]["name"]
        unless genre_name.blank?
            genre = Genre.find_or_create_by(name: genre_name)
            self.genres << genre
        end
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :require_login
    before_action only: [:edit, :update] do
        authorize_to_edit(Story)
    end

    def index
        @stories = Story.most_recent
    end
    
    def new
        @story = Story.new
    end

    def create
        @story = current_user.stories.build(story_params)
        if @story.save
            redirect_to story_path(@story)
        else
            render 'new'
        end
    end

    def show
        @story = Story.find_by_id(params[:id])
    end

    def edit
        @story = Story.find_by_id(params[:id])
    end

    def update
        @story = Story.find_by_id(params[:id])
        @story.update(story_params)
        redirect_to story_path(@story)
    end

    def destroy
        @story = Story.find_by_id(params[:id])
        @story.destroy
        redirect_to user_path(@story.user)
    end

    private

    def story_params
        params.require(:story).permit(:title, :medium, :summary, :user_id, genre_ids:[], genres_attributes: [:name])
    end
    
end

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
    <div class="form-group">
        <%= f.label :title, "Title: " %><br>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :medium, "Medium: " %><br>
        <%= f.select :medium, options_for_select([["Novel"], ["Tabletop RPG"], ["Screenplay"], ["Video Game"], ["Podcast"], ["Play"], ["Comic Book"], ["Other"]], :selected=>@story.medium), class: "form-control" %><br>
    </div>
    
    <div class="form-group">
        <%= f.label :genre, "Genres: " %><br>
        <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, class: "form-control" %><br>
    </div>

    ...or Add A New Genre:<br>
    <%= f.fields_for :genres, @story.genres.build do |genre_fields| %>
        <div class="form-group">
            <%= genre_fields.text_field :name, class: "form-control" %>
        </div>
    <% end %><br>
    
    <div class="form-group">
        <%= f.label :summary, "Summary: " %><br>
        <%= f.text_area :summary, class: "form-control" %><br>
    </div>

    <%= submit_tag "Create Story", class: "btn btn-primary" %>
<% end %>

app/views/stories/edit.html.erb
<div class="title-container">
    <h1>Edit <%= @story.title %></h1>
</div>
<%= render 'form' %>
<br>
<%= link_to "Back To Story", story_path(@story) %>

app/views/stories/index.html.erb
<div class="title-container">
    <h1>The Diamond Library</h1>
</div>

<p><b>See what our other users are creating!</b></p>
<br>

<% flash.each do |type, msg| %>
    <div>
        <b><%= msg %></b>
        <br><br>
    </div>
<% end %>

<% @stories.each do |s| %>
    <p><%= link_to s.title, story_path(s) %><br>
    Drafted by <%= s.user.author_name %> on <%= s.created_at.strftime("%B %e, 20%y") %>
    </p>
<% end %>

app/views/stories/new.html.erb
<div class="title-container">
    <h1>Tell A Story</h1>
</div>
<%= render partial: 'shared/errors', locals: {object: @story} %>
<%= render 'form' %>
<br>

app/views/stories/show.html.erb
<div class="title-container">
    <h1><%= @story.title %></h1>
    <% if current_user.id == @story.user_id.to_i %>
        <p><%= link_to "Edit Story", edit_story_path(@story), class: "btn btn-default" %>
        <%= link_to "Delete Story", story_path(@story), method: :delete, class: "btn btn-default" %></p>
    <% end %>
</div>

<h5>A <%= @story.medium %> by <%= @story.user.author_name %></h5>
<br>
<% if current_user.id == @story.user_id.to_i %>
    <p><b><%= link_to "Add A Character", new_story_character_path(@story), class: "btn btn-primary" %></b></p>
<% end %>
<br>
<h4>Genre(s):</h4>
<% if @story.genres.empty? %>
    <p><i>No Genres Added</i></p>
<% else %>
    <% @story.genres.each do |g| %>
        <ul>
            <li><%= g.name %></li>
        </ul>
    <% end %>
<% end %>    
<br>
<h4>Setting(s):</h4>
<% if @story.worlds.empty? %>
    <p><i>No Settings Established</i></p>
<% else %>
    <% @story.worlds.each do |w| %>
        <%= link_to w.name, world_path(w) %><br>
    <% end %>
<% end %>
<br>
<h4>Main Characters:</h4>
<p>
    <% @story.characters.main_characters.each do |c| %>
        <%= link_to c.name, story_character_path(c.story, c) %><br>
    <% end %>
    <% if @story.characters.empty? %>
        <i><%= "You Have No Characters" %></i>
    <% else %>
        <%= link_to "...See More Characters", story_characters_path(@story)%>
    <% end %>
</p>
<br>
<h4>Summary:</h4>
<%= field_completed?(@story, :summary, :empty?) %>