config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  resources :users, only: [:new, :create, :show]

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google_auth' 
  get '/characters/main_characters' => 'characters#main_characters'

  resources :worlds
  resources :stories
  resources :stories, only: [:show] do
    resources :characters, only: [:new, :index, :show, :edit, :destroy]
  end
  resources :characters
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>LoreScroll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <% if !logged_in? %>
              <%= link_to "LoreScroll", root_path, class: "navbar-brand" %>
            <% else %>
              <%= link_to "LoreScroll", user_path(current_user), class: "navbar-brand" %>
            <% end %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Create Your World", new_world_path %></li>
              <li><%= link_to "Tell Your Story", new_story_path %></li>
              <li><%= link_to "Worlds", worlds_path %></li>
              <li><%= link_to "Stories", stories_path %></li>
              <li><%= link_to "Log Out", signout_path, method: "delete" %></li> 
            <% else %>
              <li><%= link_to "Sign Up", new_user_path %></li>
              <li><%= link_to "Sign In", signin_path %></li>
              <li><%= link_to "Sign In With Google", "/auth/google_oauth2", method: :post %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <section class="container">
      <%= yield %>
    </section>
  </body>
</html>